config/routes.rb
Rails.application.routes.draw do
  resources :wallets
  resources :users
  resources :mining_types
  root "welcome#index"
  get "welcome/index"
  resources :coins # Gera as rotas do  CRUD
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to @mining_type, notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to @mining_type, notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy
    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type) do |form| %>
  <% if mining_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
        <% mining_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :acronym %>
    <%= form.text_field :acronym %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mining_types/edit.html.erb
<main>

  <h1>Editing Mining Type</h1>

  <%= render 'form', mining_type: @mining_type %>

  <%= link_to t('links.show'), @mining_type %> |
  <%= link_to t('links.back'), mining_types_path %>

</main>

app/views/mining_types/index.html.erb
<main>
<p id="notice"><%= notice %></p>

<h1>Tipos de Mineração</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Descrição</th>
      <th>Sigla</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.description %></td>
        <td><%= mining_type.acronym %></td>
        <td><%= link_to t('links.show'), mining_type %></td>
        <td><%= link_to t('links.edit'), edit_mining_type_path(mining_type) %></td>
        <td><%= link_to t('links.destroy'), mining_type, method: :delete, data: { confirm: t('links.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Tipo de Mineração', new_mining_type_path %>
</main>

app/views/mining_types/new.html.erb
<main>
<h1>Novo Tipos de Mineração</h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to t('links.back'), mining_types_path %>
</main>

app/views/mining_types/show.html.erb
<main>
<p id="notice"><%= notice %></p>

<p>
  <strong>Descrição:</strong>
  <%= @mining_type.description %>
</p>

<p>
  <strong>Sigla:</strong>
  <%= @mining_type.acronym %>
</p>

<%= link_to t('links.edit'), edit_mining_type_path(@mining_type) %> |
<%= link_to t('links.back'), mining_types_path %>

</main>