config/routes.rb
Rails.application.routes.draw do
  resources :wallets
  resources :users
  resources :mining_types
  root "welcome#index"
  get "welcome/index"
  resources :coins # Gera as rotas do  CRUD
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :set_wallet, only: %i[ show edit update destroy ]

  # GET /wallets or /wallets.json
  def index
    @wallets = Wallet.all
  end

  # GET /wallets/1 or /wallets/1.json
  def show
  end

  # GET /wallets/new
  def new
    @wallet = Wallet.new
  end

  # GET /wallets/1/edit
  def edit
  end

  # POST /wallets or /wallets.json
  def create
    @wallet = Wallet.new(wallet_params)

    respond_to do |format|
      if @wallet.save
        format.html { redirect_to @wallet, notice: "Wallet was successfully created." }
        format.json { render :show, status: :created, location: @wallet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wallets/1 or /wallets/1.json
  def update
    respond_to do |format|
      if @wallet.update(wallet_params)
        format.html { redirect_to @wallet, notice: "Wallet was successfully updated." }
        format.json { render :show, status: :ok, location: @wallet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallets/1 or /wallets/1.json
  def destroy
    @wallet.destroy
    respond_to do |format|
      format.html { redirect_to wallets_url, notice: "Wallet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallet
      @wallet = Wallet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wallet_params
      params.require(:wallet).permit(:descryption, :wallet_budget, :user_id)
    end
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/wallets/_form.html.erb
<%= form_with(model: wallet) do |form| %>
  <% if wallet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      <ul>
        <% wallet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descryption %>
    <%= form.text_field :descryption %>
  </div>

  <div class="field">
    <%= form.label :wallet_budget %>
    <%= form.text_field :wallet_budget %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wallets/edit.html.erb
<h1>Editing Wallet</h1>

<%= render 'form', wallet: @wallet %>

<%= link_to 'Show', @wallet %> |
<%= link_to 'Back', wallets_path %>

app/views/wallets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wallets</h1>

<table>
  <thead>
    <tr>
      <th>Descryption</th>
      <th>Wallet budget</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wallets.each do |wallet| %>
      <tr>
        <td><%= wallet.descryption %></td>
        <td><%= wallet.wallet_budget %></td>
        <td><%= wallet.user_id %></td>
        <td><%= link_to 'Show', wallet %></td>
        <td><%= link_to 'Edit', edit_wallet_path(wallet) %></td>
        <td><%= link_to 'Destroy', wallet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wallet', new_wallet_path %>

app/views/wallets/new.html.erb
<h1>New Wallet</h1>

<%= render 'form', wallet: @wallet %>

<%= link_to 'Back', wallets_path %>

app/views/wallets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descryption:</strong>
  <%= @wallet.descryption %>
</p>

<p>
  <strong>Wallet budget:</strong>
  <%= @wallet.wallet_budget %>
</p>

<p>
  <strong>User:</strong>
  <%= @wallet.user_id %>
</p>

<%= link_to 'Edit', edit_wallet_path(@wallet) %> |
<%= link_to 'Back', wallets_path %>