config/routes.rb
Rails.application.routes.draw do
  resources :wallets
  resources :users
  resources :mining_types
  root "welcome#index"
  get "welcome/index"
  resources :coins # Gera as rotas do  CRUD
end

app/models/coin.rb
class Coin < ApplicationRecord
  belongs_to :mining_type
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[show edit update destroy ]
  before_action :set_mining_type, only: %i[show edit update destroy  create new]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: "Moeda criada com Sucesso." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: "Moeda Atualizada !" }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Moeda Excluida com Sucesso." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_coin
    @coin = Coin.find(params[:id])
  end

  def set_mining_type
    @mining_type = MiningType.all.pluck(:description, :id)
  end

  # Only allow a list of trusted parameters through.
  def coin_params
    params.require(:coin).permit(:description, :acronym, :url_img, :mining_type_id)
  end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :acronym %>
    <%= form.text_field :acronym %>
  </div>

  <div class="field">
    <%= form.label :url_img %>
    <%= form.text_field :url_img %>
  </div>

  <div class="field">
    <%= form.label :mining_type_id %>
    <%= form.select("mining_type_id", @mining_type)%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<main>
<h1>Editar Moeda</h1>
  <%= stylesheet_link_tag 'coins', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= render 'form', coin: @coin %>

<%= link_to 'Show', @coin %> |
<%= link_to 'Back', coins_path %>
</main>

app/views/coins/index.html.erb
<main>
<p id="notice"><%= notice %></p>

  <h1>Moedas</h1>
  <table class="table table-hover">
    <thead>
    <tr>
      <th>Descrição</th>
      <th>Sigla</th>
      <th>Imagem</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td><%= image_tag coin.url_img, size: "50x50" %></td>
        <td><%= link_to 'Mostrar', coin %></td>
        <td><%= link_to 'Editar', edit_coin_path(coin) %></td>
        <td><%= link_to 'Excluir', coin, method: :delete, data: { confirm: 'Você tem Certerza?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br>

  <%= link_to 'Nova Moeda', new_coin_path %>

</main>

app/views/coins/new.html.erb
<main>
<h1>Nova Moeda</h1>

<%= render 'form', coin: @coin %>

<%= link_to 'Back', coins_path %>
</main>

app/views/coins/show.html.erb
<main>
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @coin.description %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @coin.acronym %>
</p>

<p>
  <strong>Url img:</strong>
  <%=  image_tag @coin.url_img %>
</p>

<%= link_to 'Edit', edit_coin_path(@coin) %> |
<%= link_to 'Back', coins_path %>
</main>